say: This is configuration/springboot/application.yml !

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
