spring:
  datasource:
    #url: jdbc:mysql://192.168.56.101:3306/me?useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    #password: 123456
    password: artorianero
    #driverClassName: com.mysql.jdbc.Driver
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL # Specify the DBMS
    show-sql: true  # Show or not log for each sql query
    hibernate:
      ddl-auto: update  # Hibernate ddl auto (create, create-drop, update)
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy # Naming strategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect # stripped before adding them to the entity manager)
